var produto1={"tipo":"mascara", "nome": "Máscara de Pano Reutilizável Dupla Camada - 1 Unidade", "preco":"R$ 2,99"};
var produto2={"tipo":"mascara", "nome": "Máscara de Pano Reutilizável Dupla Camada - 5 Unidades", "preco":"R$ 14,99"};
var produto3={"tipo":"mascara", "nome": "Máscara de Pano Reutilizável Dupla Camada - 10 Unidades", "preco":"R$ 28,99"};
var produto4={"tipo":"mascara", "nome": "Máscara de Pano Reutilizável Dupla Camada - 50 Unidades", "preco":"R$ 139,99"};
var descmasc="Bom... quando eu resolvi me candidata a presidência do grêmio estudantil, eu me candidatei por um monte de razões. O que eu nunca quis saber é se eu queria mesmo ser presidente deste grêmio. Bom...eu quero, sabe eu, eu, eu não sei o que posso fazer como presidente do grêmio, mas eu sei o que eu vou tentar fazer. Eu vou tentar consegui armários com combinações que funcione, eu estou cheio de chegar no meu armário e ver que tudo o que tinha por lá sumiu. Vou tentar conseguir livros didáticos desta década,eu tenho livros de História que diz que D'Watsen House é o presidente. Quem é D'Watsen House? Eu não sei. E a comida da cantina? Eu comi uma gelatina que estava muito mais dura que o prato. E porque tanto salaminho? Alguém aí votou em salaminho? Nós comemos mortadela? Presunto? Dá pra sair um queijinho ai? E se servem salsicha na terça-feira, eu não quero comer salsinha ensopada na quarta, e na quinta, e na sexta feijão com salsicha. Da um jeito. E a gente tem que jurar a bandeira todo dia? É uma jura, basta jurar uma vez... qual é eles não confiam na gente? E que tal fazermos um  passeios a  lugares que a gente quer mesmo ir? Já chega de tanto ir ao Jardim Botânico. Que tal o parque de diversões? Ou estádio de futebol? Vamos ver os Nicks, vamos ver os Yankees, puxa eu topo até ver Cats. Mas se a gente for ao Jardim Botânico mais uma vez, eu juro que vou arrancar os galhos de alguém."

var produto5={"tipo":"luva", "nome": "Luva de Látex Descartável - 1 Unidade", "preco":"R$ 0,99"};
var produto6={"tipo":"luva", "nome": "Luva de Látex Descartável - 5 Unidades", "preco":"R$ 4,49"};
var produto7={"tipo":"luva", "nome": "Luva de Látex Descartável - 10 Unidades", "preco":"R$ 8,99"};
var produto8={"tipo":"luva", "nome": "Luva de Látex Descartável - 100 Unidades", "preco":"R$ 38,83"};
var descluva="Bom... quando eu resolvi me candidata a presidência do grêmio estudantil, eu me candidatei por um monte de razões. O que eu nunca quis saber é se eu queria mesmo ser presidente deste grêmio. Bom...eu quero, sabe eu, eu, eu não sei o que posso fazer como presidente do grêmio, mas eu sei o que eu vou tentar fazer. Eu vou tentar consegui armários com combinações que funcione, eu estou cheio de chegar no meu armário e ver que tudo o que tinha por lá sumiu. Vou tentar conseguir livros didáticos desta década,eu tenho livros de História que diz que D'Watsen House é o presidente. Quem é D'Watsen House? Eu não sei. E a comida da cantina? Eu comi uma gelatina que estava muito mais dura que o prato. E porque tanto salaminho? Alguém aí votou em salaminho? Nós comemos mortadela? Presunto? Dá pra sair um queijinho ai? E se servem salsicha na terça-feira, eu não quero comer salsinha ensopada na quarta, e na quinta, e na sexta feijão com salsicha. Da um jeito. E a gente tem que jurar a bandeira todo dia? É uma jura, basta jurar uma vez... qual é eles não confiam na gente? E que tal fazermos um  passeios a  lugares que a gente quer mesmo ir? Já chega de tanto ir ao Jardim Botânico. Que tal o parque de diversões? Ou estádio de futebol? Vamos ver os Nicks, vamos ver os Yankees, puxa eu topo até ver Cats. Mas se a gente for ao Jardim Botânico mais uma vez, eu juro que vou arrancar os galhos de alguém."

var produto9={"tipo":"alcoolgel", "nome": "Álcool em Gel SepPro Gel 1L - 1 Unidade", "preco":"R$ 11,99"};
var produto10={"tipo":"alcoolgel", "nome": "Álcool em Gel SepPro Gel 1L - 5 Unidades", "preco":"R$ 58,99"};
var produto11={"tipo":"alcoolgel", "nome": "Álcool em Gel SepPro Gel 1L - 10 Unidades", "preco":"R$ 117,99"};
var produto12={"tipo":"alcoolgel", "nome": "Álcool em Gel SepPro Gel 1L - 100 Unidades", "preco":"R$ 1190,00"};
var descalcoolgel="Bom... quando eu resolvi me candidata a presidência do grêmio estudantil, eu me candidatei por um monte de razões. O que eu nunca quis saber é se eu queria mesmo ser presidente deste grêmio. Bom...eu quero, sabe eu, eu, eu não sei o que posso fazer como presidente do grêmio, mas eu sei o que eu vou tentar fazer. Eu vou tentar consegui armários com combinações que funcione, eu estou cheio de chegar no meu armário e ver que tudo o que tinha por lá sumiu. Vou tentar conseguir livros didáticos desta década,eu tenho livros de História que diz que D'Watsen House é o presidente. Quem é D'Watsen House? Eu não sei. E a comida da cantina? Eu comi uma gelatina que estava muito mais dura que o prato. E porque tanto salaminho? Alguém aí votou em salaminho? Nós comemos mortadela? Presunto? Dá pra sair um queijinho ai? E se servem salsicha na terça-feira, eu não quero comer salsinha ensopada na quarta, e na quinta, e na sexta feijão com salsicha. Da um jeito. E a gente tem que jurar a bandeira todo dia? É uma jura, basta jurar uma vez... qual é eles não confiam na gente? E que tal fazermos um  passeios a  lugares que a gente quer mesmo ir? Já chega de tanto ir ao Jardim Botânico. Que tal o parque de diversões? Ou estádio de futebol? Vamos ver os Nicks, vamos ver os Yankees, puxa eu topo até ver Cats. Mas se a gente for ao Jardim Botânico mais uma vez, eu juro que vou arrancar os galhos de alguém."

var produto13={"tipo":"alcool", "nome": "Álcool 70% 1L - 1 Unidade", "preco":"R$ 8,99"};
var produto14={"tipo":"alcool", "nome": "Álcool 70% 1L - 5 Unidades", "preco":"R$ 43,99"};
var produto15={"tipo":"alcool", "nome": "Álcool 70% 1L - 10 Unidades", "preco":"R$ 87,99"};
var produto16={"tipo":"alcool", "nome": "Álcool 70% 1L - 100 Unidades", "preco":"R$ 890,00"};
var descalcool="Bom... quando eu resolvi me candidata a presidência do grêmio estudantil, eu me candidatei por um monte de razões. O que eu nunca quis saber é se eu queria mesmo ser presidente deste grêmio. Bom...eu quero, sabe eu, eu, eu não sei o que posso fazer como presidente do grêmio, mas eu sei o que eu vou tentar fazer. Eu vou tentar consegui armários com combinações que funcione, eu estou cheio de chegar no meu armário e ver que tudo o que tinha por lá sumiu. Vou tentar conseguir livros didáticos desta década,eu tenho livros de História que diz que D'Watsen House é o presidente. Quem é D'Watsen House? Eu não sei. E a comida da cantina? Eu comi uma gelatina que estava muito mais dura que o prato. E porque tanto salaminho? Alguém aí votou em salaminho? Nós comemos mortadela? Presunto? Dá pra sair um queijinho ai? E se servem salsicha na terça-feira, eu não quero comer salsinha ensopada na quarta, e na quinta, e na sexta feijão com salsicha. Da um jeito. E a gente tem que jurar a bandeira todo dia? É uma jura, basta jurar uma vez... qual é eles não confiam na gente? E que tal fazermos um  passeios a  lugares que a gente quer mesmo ir? Já chega de tanto ir ao Jardim Botânico. Que tal o parque de diversões? Ou estádio de futebol? Vamos ver os Nicks, vamos ver os Yankees, puxa eu topo até ver Cats. Mas se a gente for ao Jardim Botânico mais uma vez, eu juro que vou arrancar os galhos de alguém."

var produto17={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto18={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto19={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto20={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto21={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto22={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto23={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto24={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto25={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto26={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto27={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto28={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto29={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto30={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto31={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto32={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto33={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto34={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};
var produto35={"tipo":"mascara", "nome": "Máscara De Pano Reutilizável Dupla Camada - 1 Pçs", "preco":"R$ 99,99"};